### PR TITLE
New lexer2019

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Review by JoshDreamland — APPROVED** [review]
Hah.

**Comment by JoshDreamland** [comment]
Actually, hold up. Why isn't that strbw check taking care of that? Something's fishy, there. Something bigger is probably at play.

**Comment by fundies** [comment]
because you take("clude") so both ifs will fail because by time youre at second you would have "_next"

**Comment by JoshDreamland** [comment]
Oh, okay. So strbw was doing it's job, but then it was expecting clude_next when clude had already been consumed. Let's add a branch.

**Comment by fundies** [comment]
you still call drop() in this src. im not sure why you deleted it

**Comment by JoshDreamland** [comment]
GitHub's editor didn't like it.

**Comment by JoshDreamland** [comment]
I'll just patch it locally.

**Comment by JoshDreamland** [comment]
Patched: 3fde6d1635434a6968808674fc1d5472000712ec

**Pull request closed without merging**
